### ISSUE TITLE
Monotonically increasing guarantee in the same millisecond

### ISSUE THREAD

**Issue by arjunyel** [yujiosaka/wa-ulid#1]
**What is the current behavior?**

https://github.com/perry-mitchell/ulidx/issues/14

**If the current behavior is a bug, please provide the steps to reproduce**

"given `const [a, b, c] = [ulid(), ulid(), ulid()]` c and b could sort lower than a" https://github.com/ulid/javascript/issues/74

**What is the expected behavior?**

Monotonically increasing guarantee in the same millisecond

**What is the motivation / use case for changing the behavior?**

Help with sorting

**Please tell us about your environment:**

- Version: Latest
- Platform / OS version:
- Node.js version: 20+
- Rust version:

**Comment by yujiosaka** [comment]
@arjunyel 
there is already a monotonic factory for it:
https://github.com/yujiosaka/wa-ulid?tab=readme-ov-file#monotonic-ulids

**Comment by arjunyel** [comment]
> @arjunyel there is already a monotonic factory for it: https://github.com/yujiosaka/wa-ulid?tab=readme-ov-file#monotonic-ulids

@yujiosaka yes but that factory doesn't provide guarantees in the same millisecond. If this library fixed that it would be a great reason to use it over the JavaScript library

**Comment by yujiosaka** [comment]
@arjunyel 
you mean you want the non-monotonic factory to support the monotonic behavior?

**Comment by yujiosaka** [comment]
the monotonic factory increments the least significant bit for the same milliseconds, and is tested here:
https://github.com/yujiosaka/wa-ulid/blob/383bf67cae3f00dd02fc538d37ad0ffedf2299ab/test/index.test.ts#L201-L207
